[project]
name = "hours"
version = "1.0.0"
description = "Hours Tracker CLI POC"
requires-python = ">=3.9"
dependencies = [
    "click>=8.1",
]

[project.scripts]
hours = "hours.main:cli"

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"