[project]
name = "hello"
version = "1.0.0"
description = "Hello CLI POC"
requires-python = ">=3.11"
dependencies = [
    "click>=8.1",
]

[project.scripts]
hello = "hello.main:cli"

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"