[project]
name = "db"
version = "1.0.0"
description = "Database CLI POC"
requires-python = ">=3.11"
dependencies = [
    "click>=8.1",
]

[project.scripts]
db = "db.main:cli"

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"